# Generated by Django 3.2.25 on 2026-01-15 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ExportTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', '等待中'), ('processing', '处理中'), ('completed', '已完成'), ('failed', '失败')], default='pending', max_length=20, verbose_name='状态')),
                ('file_path', models.CharField(blank=True, max_length=255, verbose_name='文件路径')),
                ('total_links', models.PositiveIntegerField(default=0, verbose_name='总链接数')),
                ('error_message', models.TextField(blank=True, verbose_name='错误信息')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='完成时间')),
            ],
            options={
                'verbose_name': '导出任务',
                'verbose_name_plural': '导出任务',
                'db_table': 'export_tasks',
                'ordering': ['-created_at'],
            },
        ),
    ]
