# Generated by Django 3.2.25 on 2026-01-15 07:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('links', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='tag',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tags', to=settings.AUTH_USER_MODEL, verbose_name='用户'),
        ),
        migrations.AddField(
            model_name='link',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='links', to='links.group', verbose_name='分组'),
        ),
        migrations.AddField(
            model_name='link',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='links', to='links.Tag', verbose_name='标签'),
        ),
        migrations.AddField(
            model_name='link',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='links', to=settings.AUTH_USER_MODEL, verbose_name='用户'),
        ),
        migrations.AddField(
            model_name='group',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='link_groups', to=settings.AUTH_USER_MODEL, verbose_name='用户'),
        ),
        migrations.AddField(
            model_name='accesslog',
            name='link',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='access_logs', to='links.link', verbose_name='链接'),
        ),
        migrations.AlterUniqueTogether(
            name='tag',
            unique_together={('user', 'name')},
        ),
        migrations.AddIndex(
            model_name='link',
            index=models.Index(fields=['user', 'created_at'], name='links_user_id_cdc31d_idx'),
        ),
        migrations.AddIndex(
            model_name='link',
            index=models.Index(fields=['short_code'], name='links_short_c_95d67d_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='group',
            unique_together={('user', 'name')},
        ),
        migrations.AddIndex(
            model_name='accesslog',
            index=models.Index(fields=['link', 'accessed_at'], name='access_logs_link_id_4a8d60_idx'),
        ),
    ]
